
name: Build

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Java ${{ matrix.java }} Maven
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8,11]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build Project
        run: ./mvnw ${MAVEN_ARGS} clean install

      - name: Check java-generator CLI
        run: |
          chmod a+x java-generator/cli/target/java-gen
          java-generator/cli/target/java-gen --source=java-generator/core/src/test/resources/crontab-crd.yml --target=./tmp
